# fonud here https://pnpm.io/continuous-integration
version: 2.1

jobs:
  build: # this can be any name you choose
    docker:
      - image: node:18-bullseye #raw 18 fails: https://github.com/nodejs/docker-node/issues/1916
    resource_class: medium+
    parallelism: 10

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Test with jest
          command: |
            node --experimental-vm-modules node_modules/jest/bin/jest.js